name: 'Setup Pip Environment'
description: 'Creates and activates a virtual environment or sets up pip with --user flag to avoid externally-managed-environment errors'

runs:
  using: 'composite'
  steps:
    - name: Setup Pip Environment
      id: pip_env
      shell: bash
      run: |
        # Ensure basic system PATH is available
        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

        # Use python3 if python doesn't work, fallback to python
        if command -v python3 &> /dev/null && python3 -m pip --version &>/dev/null; then
          PYTHON_CMD="python3"
        elif command -v python &> /dev/null && python -m pip --version &>/dev/null; then
          PYTHON_CMD="python"
        else
          echo "Error: Neither python nor python3 with pip is available"
          exit 1
        fi

        # Create virtual environment to avoid externally-managed-environment error
        VENV_DIR="$HOME/venv"
        echo "Creating virtual environment at $VENV_DIR..."

        # Try to create venv with pip first
        if $PYTHON_CMD -m venv "$VENV_DIR" 2>/dev/null; then
          echo "Virtual environment created with pip"
        # If that fails, try without pip and install pip manually
        elif $PYTHON_CMD -m venv --without-pip "$VENV_DIR" 2>/dev/null; then
          echo "Virtual environment created without pip, installing pip..."
          # Install pip in the venv using get-pip.py
          /usr/bin/curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || /bin/curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || true
          if [ -f /tmp/get-pip.py ] && [ -f "$VENV_DIR/bin/python" ]; then
            "$VENV_DIR/bin/python" /tmp/get-pip.py 2>&1 || true
            /bin/rm -f /tmp/get-pip.py
          fi
        # If venv module doesn't work, try installing python3-venv
        else
          echo "venv module not available, trying to install python3-venv..."
          if command -v /usr/bin/apt-get &> /dev/null; then
            sudo /usr/bin/apt-get update && sudo /usr/bin/apt-get install -y python3-venv || true
            # Try again after installing python3-venv
            if $PYTHON_CMD -m venv "$VENV_DIR" 2>/dev/null; then
              echo "Virtual environment created after installing python3-venv"
            elif $PYTHON_CMD -m venv --without-pip "$VENV_DIR" 2>/dev/null; then
              echo "Virtual environment created without pip, installing pip..."
              /usr/bin/curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || /bin/curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || true
              if [ -f /tmp/get-pip.py ] && [ -f "$VENV_DIR/bin/python" ]; then
                "$VENV_DIR/bin/python" /tmp/get-pip.py 2>&1 || true
                /bin/rm -f /tmp/get-pip.py
              fi
            fi
          fi
        fi

        # Activate virtual environment if it exists and has pip
        if [ -f "$VENV_DIR/bin/activate" ] && [ -f "$VENV_DIR/bin/pip" ]; then
          source "$VENV_DIR/bin/activate"
          echo "$VENV_DIR/bin" >> $GITHUB_PATH
          export PATH="$VENV_DIR/bin:$PATH"
          echo "Virtual environment activated with pip"
          echo "pip_cmd=pip" >> $GITHUB_OUTPUT
          echo "pip_flag=" >> $GITHUB_OUTPUT
        elif [ -f "$VENV_DIR/bin/activate" ]; then
          # Venv exists but no pip - try to use system pip with --user
          echo "Warning: Virtual environment created but pip not available, using --user flag"
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "pip_cmd=$PYTHON_CMD -m pip" >> $GITHUB_OUTPUT
          echo "pip_flag=--user" >> $GITHUB_OUTPUT
        else
          echo "Warning: Virtual environment not created, using --user flag as fallback"
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "pip_cmd=$PYTHON_CMD -m pip" >> $GITHUB_OUTPUT
          echo "pip_flag=--user" >> $GITHUB_OUTPUT
        fi
      env:
        HOME: ${{ github.workspace }}/.home

